In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
digits=load_digits()

In [12]:
#splitting the datsets into training and teting
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [17]:
#1->use logistic regression
model1=LogisticRegression()
model1.fit(X_train,y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [18]:
model1.score(X_test,y_test)

0.9685185185185186

In [22]:
#2->use SVM
model2=SVC()
model2.fit(X_train,y_train)

SVC()

In [23]:
model2.score(X_test,y_test)

0.9814814814814815

In [26]:
model3=RandomForestClassifier()
model3.fit(X_train,y_train)

RandomForestClassifier()

In [27]:
model3.score(X_test,y_test)

0.9666666666666667

In [28]:
#now above we have done with train_test_split method

In [29]:
#now we go for KFold
from sklearn.model_selection import KFold

In [40]:
kf=KFold(n_splits=9)#how many fold yuou want to craete

In [41]:
kf

KFold(n_splits=9, random_state=None, shuffle=False)

In [42]:
#to check the working
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[1 2 3 4 5 6 7 8] [0]
[0 2 3 4 5 6 7 8] [1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


In [43]:
 def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [44]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [45]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9814814814814815

In [47]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9722222222222222

In [48]:
from sklearn.model_selection import StratifiedKFold

In [49]:
folds=StratifiedKFold(n_splits=3)

In [50]:
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [55]:
scores_log=[]
scores_svc=[]
scores_rf=[]

for train_index,test_index in folds.split(digits.data,digits.target):
  X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  scores_log.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
  scores_svc.append(get_score(SVC(),X_train,X_test,y_train,y_test))
  scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [56]:
scores_log

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [57]:
scores_svc

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [58]:
scores_rf

[0.9398998330550918, 0.9649415692821369, 0.9332220367278798]

In [59]:
#now nwe understand the logic we can directly use sklearn

In [60]:
from sklearn.model_selection import cross_val_score

In [61]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [62]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [65]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.925     , 0.90833333, 0.95264624, 0.9637883 , 0.93314763])

In [66]:
#So this is inbuilt one to perform K fold method although we have practically implemented it from scartch

In [67]:
#uptill now we have cmpared differnet classifier , we can also compare same model with different parmeters thi is called parametic tuning

In [70]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93888889, 0.91111111, 0.95264624, 0.96657382, 0.93036212])

In [72]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.85833333, 0.80277778, 0.8913649 , 0.86908078, 0.83844011])

In [73]:
#Exercise Part Start

In [75]:
from sklearn.datasets import load_iris
iris=load_iris()

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [81]:
import pandas as pd

Logistic Regression

In [86]:
scores_log=cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [87]:
scores_log

array([0.98, 0.96, 0.98])

In [88]:
np.average(scores_log)

0.9733333333333333

Decison Tree

In [90]:
scores_dt=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)

In [91]:
scores_dt

array([0.98, 0.92, 0.98])

In [92]:
np.average(scores_dt)

0.96

Supprt Vector Machine

In [93]:
scores_svm=cross_val_score(SVC(),iris.data,iris.target,cv=3)

In [94]:
scores_svm


array([0.96, 0.98, 0.94])

In [95]:
np.average(scores_svm)

0.96

Random Forest

In [96]:
scores_rf=cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3)

In [97]:
scores_rf

array([0.98, 0.94, 0.98])

In [98]:
np.average(scores_rf)

0.9666666666666667

# **Best Decison so far-> Logistic Regression ->0.9733333**