In [1]:
from google.colab import files
uploaded = files.upload()

Saving homeprices.csv to homeprices.csv


In [2]:
import numpy as np
import pandas as pd


In [3]:
df=pd.read_csv('homeprices.csv')

In [4]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
from sklearn import linear_model
reg=linear_model.LinearRegression()

In [6]:
reg.fit(df[['area']],df.price)

LinearRegression()

In [7]:
reg.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [8]:
#working fine my ml model
#now let's try to save it
import pickle

In [11]:
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [12]:
from google.colab import files
files.download('model_pickle')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [13]:
#now we can directly use this trained model
with open('model_pickle','rb') as f:
  model=pickle.load(f)

In [14]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [16]:
#doing same thing with more effiint method using joblib
import joblib

In [17]:
joblib.dump(reg,'modlib')

['modlib']

In [18]:
from google.colab import files
files.download('modlib')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [19]:
ans=joblib.load('modlib')

In [20]:
ans.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [21]:
ans.coef_

array([135.78767123])

In [22]:
ans.intercept_

180616.43835616432